### PR TITLE
style for scrollbar

### PR DESCRIPTION
**Pull request by progressify**
I have added the style for the scrollbar
this is the example: https://progressify.dev

### CODE REVIEW

**Comment by ertuil** [comment]
Great thanks for your excellent work and contribution. However, I prefer the default scrollbar style personally for popular aesthetic and compatibility consideration.I am sorry I may not be able to merge your commit into `master` branch. But there are two ways to value your work and provide various options:
1. merge your commit into a new branch and refer it from `readme.md`
2. or directly refer your repository in `readme.md`
In both cases, I would like to add your name in `CONTRIBUTION` if you will.

Please let me know which one is better to you. If you have any other thoughts, do not hesitate to let me know.

Thanks again.

**Comment by progressify** [comment]
What name do you prefer for the new branch?

**Comment by ertuil** [comment]
What about your username? Or do you have any other suggestions?

**Comment by ertuil** [comment]
Do we have an agreement about the branch name? Any other names are also free to use, just name it.

**Comment by progressify** [comment]
I am thinking of a name that has some reference to the scrollbar.
colorful-scrollbar
styled-scrollbar
tinted-scrollbar
i don't know xD

**Comment by akloya** [comment]
i added your scroll bar code but i dont get they typewriter content as per ur example @progressify 
do i have to edit any other html files.

**Comment by progressify** [comment]
> i added your scroll bar code but i dont get they typewriter content as per ur example @progressify
> do i have to edit any other html files.

hi @akloya 
this pull request integrate only the CSS for the scrollbar.
for typewriter effect you must to follow my blog post (sorry only in Italian).
https://progressify.dev/post/hugo/effetto-macchina-da-scrivere-con-typewriterjs/

**Pull request merged**
